# Blog
keywords: Hexo,HTML,CSS,php,Python,Node.js
author: 天空之城,zhangykvip@126.com
description: live a good life.
avatar: /images/favicon.png

# Social Accounts
twitter: 
rss: atom.xml
weibo: http://weibo.com/jaakzh
instagram: 
github: https://github.com/zhangyake/
facebook: 

# Comment
duoshuo: 
disqus: 
gentie: zhangykvip@126.com
